// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDe79eWvgWuDEThKcfN55MQdWlmijoGmM',
    appId: '1:770023908940:web:1e76f273518d546ab9b6e9',
    messagingSenderId: '770023908940',
    projectId: 'logincounter-next',
    authDomain: 'logincounter-next.firebaseapp.com',
    storageBucket: 'logincounter-next.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYeZ0JJePZE_Xjg3IuIh06MG2ARLDgvkA',
    appId: '1:770023908940:android:d49d681d2b48cca1b9b6e9',
    messagingSenderId: '770023908940',
    projectId: 'logincounter-next',
    storageBucket: 'logincounter-next.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDBzNeaeJjaxanCucGXidhtPDjMa-Q1vA',
    appId: '1:770023908940:ios:37ea4286bb88238bb9b6e9',
    messagingSenderId: '770023908940',
    projectId: 'logincounter-next',
    storageBucket: 'logincounter-next.appspot.com',
    iosBundleId: 'com.example.counterNext',
  );
}
